name: Windows (MSVS) Build
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: ["Win32", "x64"]
        include:
          - arch: "Win32"
            package: "system3-sdl2-32bit"
          - arch: "x64"
            package: "system3-sdl2-64bit"
    name: MSVS ${{ matrix.arch }}
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Build
      run: |
        mkdir out
        cd out
        cmake -G "Visual Studio 17 2022" -A ${{ matrix.arch }} ../
        cmake --build . --config Release
        cmake --install . --prefix artifacts
        cp ../COPYING.txt artifacts/

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.package }}
        path: out/artifacts
